### ISSUE TITLE
Static serving is broken

### ISSUE THREAD

**Issue by Ichabond** [zofrex/better-than-basic#2]
Currently, the serving of static content (specifically, /login/static/style.css) returns a 404 error from the better-than-basic service binary. 
This is shown clearly through interception with tcpdump:
`17:05:18.765066 IP localhost.3000 > localhost.46616: Flags [P.], seq 1:83, ack 432, win 350, options [nop,nop,TS val 1029751658 ecr 1029751658], length 82
E...g.@.@..u................}......^.z.....
=`.j=`.jHTTP/1.0 404 Not Found`
An strace of /usr/sbin/better-than-basic returns no read() or fopen() calls to the style.css file upon hitting the /login/static/style.css endpoint.

**Comment by zofrex** [comment]
Should be fixed in [0.1.1](https://github.com/zofrex/better-than-basic/releases/tag/0.1.1-prealpha)... let me know!

**Comment by Ichabond** [comment]
Yup, resolved.
